### ISSUE TITLE
Wasm-pack installation required

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed-quickstart#10]
Related PR from Seed repo: https://github.com/David-OConnor/seed/pull/185

quickstart's `Makefile.toml`:
```toml
[tasks.create_wasm]
description = "Build with wasm-pack"
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--target", "no-modules", "--out-name", "package", "--dev"]

[tasks.create_wasm_release]
description = "Build with wasm-pack"
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--target", "no-modules", "--out-name", "package"]
```

also quickstart's `Makefile.toml`:
```toml
[tasks.test]
description = "Run tests. Ex: 'cargo make test firefox'. Test envs: [chrome, firefox, safari]"
clear = true
workspace = false
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["test", "--${@}"]
```

See `install_crate`. The first two tasks should be probably updated with 
```toml
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
```
